name = "Create Modpack With Bros"
author = "goodmatthew2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fe2efaab7eaf271e2a1fd709476bf7a99d606e981c6dfc43e5811b09c819942"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
