name = "Create Modpack With Bros"
author = "goodmatthew2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70c4381406c78333fd002366db6d26abb2362b35f92659d93719f5d70a3186e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
