name = "Create Modpack With Bros"
author = "goodmatthew2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16e96f9118dcbd48f40cf5a02bd0cdbbda77210d150b1863779c89125dfc0a15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
